#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-safe_yaml
Version  : 1.0.4
Release  : 3
URL      : https://rubygems.org/downloads/safe_yaml-1.0.4.gem
Source0  : https://rubygems.org/downloads/safe_yaml-1.0.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-safe_yaml-bin
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-hashie
BuildRequires : rubygem-heredoc_unindent
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
SafeYAML
========
[![Build Status](https://travis-ci.org/dtao/safe_yaml.png)](http://travis-ci.org/dtao/safe_yaml)
[![Gem Version](https://badge.fury.io/rb/safe_yaml.png)](http://badge.fury.io/rb/safe_yaml)

%package bin
Summary: bin components for the rubygem-safe_yaml package.
Group: Binaries

%description bin
bin components for the rubygem-safe_yaml package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n safe_yaml-1.0.4
gem spec %{SOURCE0} -l --ruby > rubygem-safe_yaml.gemspec

%build
gem build rubygem-safe_yaml.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
safe_yaml-1.0.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/safe_yaml-1.0.4
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/safe_yaml-1.0.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Deep/cdesc-Deep.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Deep/copy-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Deep/freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/LibyamlChecker/cdesc-LibyamlChecker.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/LibyamlChecker/libyaml_patched%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/LibyamlChecker/libyaml_version_ok%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/Date/cdesc-Date.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/Date/value-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/Hexadecimal/cdesc-Hexadecimal.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/Hexadecimal/value-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/Sexagesimal/cdesc-Sexagesimal.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/Sexagesimal/value-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Parse/cdesc-Parse.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/add_to_current_structure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/alias-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/cdesc-PsychHandler.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/end_current_structure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/end_document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/end_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/end_sequence-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/scalar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/start_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/start_sequence-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychHandler/streaming%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/cdesc-PsychResolver.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/get_node_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/get_node_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/get_node_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/native_resolve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/resolve_alias-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/resolve_root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/PsychResolver/value_is_quoted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/cdesc-Resolver.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/get_and_check_node_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/merge_into_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/normalize_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/resolve_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/resolve_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/resolve_scalar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/resolve_seq-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Resolver/tag_is_whitelisted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SafeToRubyVisitor/accept-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SafeToRubyVisitor/cdesc-SafeToRubyVisitor.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SafeToRubyVisitor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/cdesc-SyckResolver.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/get_node_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/get_node_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/get_node_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/native_resolve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/SyckResolver/value_is_quoted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToBoolean/cdesc-ToBoolean.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToBoolean/transform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToDate/cdesc-ToDate.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToDate/transform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToFloat/cdesc-ToFloat.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToFloat/transform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToFloat/try_edge_cases%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToInteger/cdesc-ToInteger.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToInteger/transform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToInteger/try_edge_cases%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToNil/cdesc-ToNil.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToNil/transform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToSymbol/cdesc-ToSymbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/ToSymbol/transform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/CaseAgnosticMap/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/CaseAgnosticMap/cdesc-CaseAgnosticMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/CaseAgnosticMap/freeze-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/CaseAgnosticMap/include%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/CaseAgnosticMap/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/ClassMethods/set_predefined_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/cdesc-TransformationMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/TransformationMap/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/cdesc-Transform.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/to_guessed_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/Transform/to_proper_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/cdesc-SafeYAML.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/load_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/restore_defaults%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/tag_is_explicitly_trusted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/tag_safety_check%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/whitelist%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/SafeYAML/whitelist_class%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/SafeYAML/cdesc-SafeYAML.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/Syck/cdesc-Syck.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/cdesc-YAML.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/filename_and_options_from_arguments-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/load_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/load_file_with_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/load_with_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/options_for_safe_load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/safe_load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/safe_load_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/safe_mode_from_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/unsafe_load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/YAML/unsafe_load_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/safe_yaml-1.0.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/CHANGES.md
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/README.md
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/bin/safe_yaml
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/bundle_install_all_ruby_versions.sh
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/deep.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/libyaml_checker.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/hexadecimal.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/sexagesimal.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_handler.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/resolver.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/safe_to_ruby_visitor.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/syck_hack.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/syck_node_monkeypatch.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/syck_resolver.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/to_boolean.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/to_date.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/to_float.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/to_integer.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/to_nil.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/to_symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/transform/transformation_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/run_specs_all_ruby_versions.sh
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/safe_yaml.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/exploit.1.9.2.yaml
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/exploit.1.9.3.yaml
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/issue48.txt
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/issue49.yml
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/libyaml_checker_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/psych_resolver_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/resolver_specs.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/safe_yaml_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/support/exploitable_back_door.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/syck_resolver_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/transform/base64_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/transform/to_date_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/transform/to_float_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/transform/to_integer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/transform/to_symbol_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/spec/yaml_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/safe_yaml-1.0.4.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/safe_yaml
